### ISSUE TITLE
Auto start idling on startup

### ISSUE THREAD

**Issue by Nevenit** [zevnda/steam-game-idler#35]
### Describe the feature

Not sure if this is a common use case but i just use the program to boost my play time in some meme games. I have to manually start idling each game and it would be nice if it automatically started to idle those games in the background as soon as the program starts.

### Which branch of SGI?

Base

**Comment by probablyraging** [comment]
Thank you for the feature request mate, though I probably wont add something like this as I feel manually idling a games is a simple process that only takes a few seconds.

What I recommend is to add all the games that you want to idle to your favorites list, hover each game in the list and click the play button, this process takes less than 1 second per game, you can only idle a max of 32 games concurrently, so realistically you can idle all 32 games is less than 30 seconds. 

Hope that makes sense, thanks again .🍻

**Comment by zevnda** [comment]
This has been added in [v1.5.29](https://github.com/zevnda/steam-game-idler/releases/tag/1.5.29)

  - Add a max of 32 games to the `auto idle` list by clicking the 3 vertical dots on a game's card
  - View games in the `auto idle` list by choosing it from the drop down `filter` menu
  - When SGI launches, all games in this list will be automatically idled
  
Thanks again for the suggestion.
