### ISSUE TITLE
Well... i have plenty of games but as soon as i start card farming it would write

### ISSUE THREAD

**Issue by HellHand87** [zevnda/steam-game-idler#47]
Well... i have plenty of games but as soon as i start card farming it would write
```
Dec 13 17:45:01.662 | [v1.5.25] [Card Farming] No games left - stopping
Dec 13 17:44:37.441 | [v1.5.25] [Card Farming] No games left - stopping
```

_Originally posted by @HellHand87 in https://github.com/zevnda/steam-game-idler/issues/44#issuecomment-2541558184_

**Comment by zevnda** [comment]
Go to your Steam profile > edit profile > privacy settings > make sure "my profile" and "game details" are set to public.

Make sure your `seassionId` and `steamLoginSecure` are correct. Log in and back out to refresh both cookies.

In SGI go to settings > card farming > enable "all games with drops" and try starting card farming again.

If all that fails, upload your `log.txt` file

**Comment by zevnda** [comment]
Are you sure you have any valid card drops remaining on your account? I see 4 games that you manually tried to farm cards on
```
Dec 13 03:32:16.319 + [v1.5.25] [Card Farming] Added Stronghold HD (40950)
Dec 13 03:31:39.908 + [v1.5.25] [Card Farming] Added Party Hard Tycoon (513330)
Dec 13 03:31:04.669 + [v1.5.25] [Card Farming] Added Hatred (341940)
Dec 13 03:30:51.128 + [v1.5.25] [Card Farming] Added Don't Starve Together (322330)
```
all of which responded with `0 cards remaining - removing from list`

Double check the games you've added actually have card drop remaining. Go to your Steam profile > badges > scroll down or press CTRL+F to search for the game's title. In the top right it will show you if a game still has card drops remaining or not.
![image](https://github.com/user-attachments/assets/67a6ef2c-f0de-4f72-8132-36b025551908)

**Comment by zevnda** [comment]
You can only get about half the amount of total cards the game has, once you get them all your game will show `no card drops remaining`. You can get booster packs to unlock more cards though. F2P games require in-game purchases to drop cards.

I would recommend reading the [FAQs Steam has regarding trading card](https://steamcommunity.com/tradingcards/faq/)

**Is there a limit to how many trading cards can drop?**

> Most games will drop a number of cards equal to about half the number of cards in that game's set of cards. For example, Half-Life 2 has 8 cards in its set, you can receive 4 card drops by playing it. You'll need to collect the other half of the set from other community members. Try the beta group discussions, community market, barter with friends, and trade discussions. You can check how many drops you have remaining on [your badges page](http://steamcommunity.com/my/badges).

**How can I get a booster pack?**

> Once you have received all of your card drops, you become eligible for a booster pack, which is a set of 3 trading cards that may include both basic and foil cards. Booster packs are granted randomly to eligible users as more badges are crafted by members of the community. Make sure you log in to Steam each week to maintain eligibility.

**What about free to play games like Team Fortress 2 or Dota 2?**

> Free to play games drop game cards based on your in-game purchasing. For every $9 USD spent (approximate) since the start of the Steam Trading Card Beta, you will earn one card drop. This card will drop at some point as you play. If you have made in-game purchases in Dota 2 or Team Fortress 2 prior to the Steam Trading Card Beta, or if you owned Team Fortress 2 prior to the Free to Play update, you will have 4 or 5 additional card drops available.

I'm going to close this issue now as I believe this has been solved. If you have any more questions, let me know.
