### ISSUE TITLE
Auto idle at startup

### ISSUE THREAD

**Issue by TiimmyTuurner** [zevnda/steam-game-idler#48]
### Describe the feature

I think it would be nice to automatically idle a pre-selected game at startup. For example, if you choose Just Cause 2 as the game to auto-idle, it will start idling automatically the next time you start your PC.

### Which branch of SGI?

Base

**Comment by zevnda** [comment]
Thanks for the feature request, this was actually already requested In #35, At that time I decided not to add such a feature but I guess I can add it and see how it goes.

My way of implementing this would be similar to how the automated `card farming` and `achievement unlocker` lists work. You would add games to an `auto idle` list _(a max of 32 games)_, and when SGI is launched those games would be automatically idled.

Give me a day or two and I'll get this added.

**Comment by TiimmyTuurner** [comment]
Thanks for the reply! I'll look forward to it!

**Comment by zevnda** [comment]
This has been added in [v1.5.29](https://github.com/zevnda/steam-game-idler/releases/tag/1.5.29)

  - Add a max of 32 games to the `auto idle` list by clicking the 3 vertical dots on a game's card
  - View games in the `auto idle` list by choosing it from the drop down `filter` menu
  - When SGI launches, all games in this list will be automatically idled
  
Thanks again for the suggestion.
