### ISSUE TITLE
Login problem

### ISSUE THREAD

**Issue by FireLostBoy-Tech** [zevnda/steam-game-idler#49]
### Describe the feature

Hey, I have a problem and when I log in with SteamLoginSecure and SessionID, something like this comes out: "Incorrect credentials"

Could that be because you still need a steam parent?
I have to include it because I have a family mode.

### Which branch of SGI?

Base

**Comment by zevnda** [comment]
Thanks for letting me know mate. I had no idea this could be an issue with parental restricted Steam accounts.

I have added a `steamParental/steamMachineAuth` input field to `settings > card farming` in [v1.5.29](https://github.com/zevnda/steam-game-idler/releases/tag/1.5.29)

Paste your `steamParental` cookie in to that field before saving and it should authorize.

**Comment by FireLostBoy-Tech** [comment]
Thank you for the quick update, I tested it immediately and logging in works now, the only problem is that my Steam credentials seem to be deleted somehow when I start card farming and therefore I can't use this function. There are no errors in the logs either, not even when I started the card farming function
