### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Dr4gOnsFuRy** [zevnda/steam-game-idler#50]
### Describe the issue

Hi, since the new update I cannot get the card farming to work, it was working perfectly fine in the version before. Nothing happens when I go to farm now and I get this message in the logs:
[v1.5.29] [Error] in (startCardFarming): invalid args `steamid` for command `validate_session`: command validate_session missing required key steamid
My session ID and steamloginsecure are both inputted, I am logged in as it shows and have even tried reinstalling but keep getting the same error message.
[log.txt](https://github.com/user-attachments/files/18183536/log.txt)

### Which branch of SGI?

Base

### What version of SGI are you using?

Latest version

### Pre-report checklist

- [X] I have checked for similar [open/closed issues](https://github.com/zevnda/steam-game-idler/issues?q=)
- [X] I have checked the [FAQ wiki](https://github.com/zevnda/steam-game-idler/wiki/faq) for my issue
- [X] I have included my "log.txt" file located in "C:\\Users\\your_username\\AppData\\Roaming\\steam-game-idler"

**Comment by zevnda** [comment]
Thanks for reporting mate.

This is fixed in [v1.5.30](https://github.com/zevnda/steam-game-idler/releases/tag/1.5.30).

SGI will automatically update the next time you launch it.

**Comment by Dr4gOnsFuRy** [comment]
Thank you, appreciate the quick response and update. All working now 👍
