### ISSUE TITLE
card farming function bug

### ISSUE THREAD

**Issue by FireLostBoy-Tech** [zevnda/steam-game-idler#51]
### Describe the issue

https://github.com/user-attachments/assets/886f7704-8e25-4df1-aa3c-9f272ff8f4ca

### Steps to reproduce the issue

Thank you for the quick update, I tested it immediately and logging in works now, the only problem is that my Steam credentials seem to be deleted somehow when I start card farming and therefore I can't use this function. There are no errors in the logs either, not even when I started the card farming function
[log.txt](https://github.com/user-attachments/files/18188026/log.txt)

### Which branch of SGI?

Base

### What version of SGI are you using?

Latest version

### Pre-report checklist

- [X] I have checked for similar [open/closed issues](https://github.com/zevnda/steam-game-idler/issues?q=)
- [X] I have checked the [FAQ wiki](https://github.com/zevnda/steam-game-idler/wiki/faq) for my issue
- [X] I have included my "log.txt" file located in "C:\\Users\\your_username\\AppData\\Roaming\\steam-game-idler"

**Comment by zevnda** [comment]
Thank you mate, sorry about that. I thought I fixed this in `1.5.30`, but apparently not.

Should now be fixed in [v1.5.31](https://github.com/zevnda/steam-game-idler/releases/tag/1.5.31)
