### ISSUE TITLE
auto hour farmer

### ISSUE THREAD

**Issue by rqdroid5** [zevnda/steam-game-idler#53]
### Describe the feature

a ability to add games to a autofarm list, when autostart on startup is on it will automatically farm hours in the selected games without any hassle

### Which branch of SGI?

Base

### Is your feature request related to an issue?

No

**Comment by zevnda** [comment]
Hey mate, I appreciate the suggestion. This is already a feature called `auto idle`, you can [read more about it here](https://github.com/zevnda/steam-game-idler/wiki/Features#auto-game-idle)

Unless I am confused by what you're asking?
