### ISSUE TITLE
Add achievement unlocking on cli

### ISSUE THREAD

**Issue by paolo-caroni** [zevnda/steam-game-idler#55]
### Describe the feature

Please add the unlocking achievement function on CLI version.
I have lost some achievement of one game when I was offline and I can't reenable it (I have also open a ticket on steam but with no luck).
I have read that the msi version have this functionality, please add this function also on the CLI multiplatform version!!!

Thanks

### Which branch of SGI?

CLI + WebUI

### Is your feature request related to an issue?

No

**Comment by zevnda** [comment]
I appreciate the suggestion, and while I wish I could add this as a feature to the CLI version, It can't be done, unfortunately. Well, it kind of can, but it would be pretty pointless.

Most people choose the CLI version so they can run SGI in a headless environment, such as on servers. As headless environments have no GUI, the Steam client doesn't function properly, and with no Steam client, there is no way to leverage the Steamworks SDK that SGI uses for modifying achievements among other things. So the only way it would work is to run the CLI version in an environment with a GUI, at which point you may as well just use the main version.

Now the issue there is that the main version of SGI is currently only Windows compatible, but I do have plans on making it cross-platform, and with its own CLI, but that is going to take pretty much a top-to-bottom re-write of the backend, as well as switching the current C# library for a cross-platform compatible one. Right now I just don't have that type of time on my hands, and even with cross-platform support, you would still need a GUI for some of the functionality that SGI offers.

Hope that clears it up.
